# Generated by Django 5.2.1 on 2025-05-10 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='admin_notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification', models.FileField(upload_to='')),
                ('date', models.DateField()),
                ('time', models.TimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('details', models.TextField()),
                ('image', models.FileField(max_length=500, upload_to='')),
                ('type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='camera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camera_id', models.BigIntegerField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('details', models.CharField(max_length=100)),
                ('phone', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='dangerous_spot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='forest_division',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('place', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='forest_officer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('phone', models.BigIntegerField()),
                ('email', models.CharField(max_length=100)),
                ('image', models.FileField(upload_to='')),
                ('dob', models.DateField(null=True)),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='login_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='RegularUserLogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='safety_tips',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tip_name', models.CharField(max_length=100)),
                ('tip_file', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='camera_alerts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('ANIMAL', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.animal')),
                ('CAMERA', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.camera')),
            ],
        ),
        migrations.CreateModel(
            name='daily_reports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report', models.FileField(upload_to='')),
                ('date', models.DateField()),
                ('OFFICER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.forest_officer')),
            ],
        ),
        migrations.CreateModel(
            name='curfew_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curfew_name', models.CharField(max_length=50)),
                ('curfew_details', models.CharField(max_length=100)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('affected_area', models.CharField(max_length=100)),
                ('threat_level', models.CharField(max_length=50)),
                ('OFFICER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.forest_officer')),
            ],
        ),
        migrations.CreateModel(
            name='alert_to_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('affected_area', models.CharField(max_length=100)),
                ('threat_level', models.CharField(max_length=100)),
                ('action_to_take', models.CharField(max_length=100)),
                ('CAMERA_ALERT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.camera_alerts')),
                ('OFFICER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.forest_officer')),
            ],
        ),
        migrations.CreateModel(
            name='forest_station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('place', models.CharField(max_length=100)),
                ('phone', models.BigIntegerField()),
                ('DIVISION', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.forest_division')),
            ],
        ),
        migrations.AddField(
            model_name='forest_officer',
            name='STATION',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.forest_station'),
        ),
        migrations.AddField(
            model_name='forest_officer',
            name='LOGIN',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.login_table'),
        ),
        migrations.CreateModel(
            name='user_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('place', models.CharField(max_length=100)),
                ('pin', models.BigIntegerField()),
                ('phone', models.BigIntegerField()),
                ('email', models.CharField(max_length=100)),
                ('image', models.FileField(upload_to='')),
                ('REGULAR_LOGIN', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.regularuserlogin')),
            ],
        ),
        migrations.CreateModel(
            name='trekking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Trekking_area', models.CharField(max_length=50)),
                ('No_of_trekkers', models.IntegerField()),
                ('Purpose_of_trek', models.CharField(max_length=100)),
                ('Emergency_contact_no', models.BigIntegerField()),
                ('Requested_date', models.DateField()),
                ('Requested_time', models.TimeField()),
                ('ID_proof', models.FileField(upload_to='')),
                ('USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user_table')),
            ],
        ),
        migrations.CreateModel(
            name='feedback_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.TextField()),
                ('date', models.DateField(auto_now_add=True)),
                ('USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user_table')),
            ],
        ),
        migrations.CreateModel(
            name='complaints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=100)),
                ('reply', models.CharField(max_length=100)),
                ('USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user_table')),
            ],
        ),
        migrations.CreateModel(
            name='user_upload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='')),
                ('animal', models.CharField(max_length=50)),
                ('latitude', models.CharField(max_length=50)),
                ('longitude', models.BigIntegerField()),
                ('type', models.BigIntegerField()),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('location_details', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=20)),
                ('USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user_table')),
            ],
        ),
    ]
