# Generated by Django 5.2.1 on 2025-05-10 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_table',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
