# Generated by Django 5.2.1 on 2025-05-10 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_user_table_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
