# Generated by Django 5.2.1 on 2025-05-11 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_animal_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_upload',
            name='type',
        ),
        migrations.AddField(
            model_name='user_upload',
            name='animal_type',
            field=models.CharField(default='unknown_animal', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user_upload',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user_upload',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='user_upload',
            name='latitude',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user_upload',
            name='longitude',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user_upload',
            name='status',
            field=models.CharField(choices=[('verified', 'Verified'), ('pending_investigation', 'Pending Investigation'), ('under_investigation', 'Under Investigation')], default='pending_investigation', max_length=30),
        ),
        migrations.AlterField(
            model_name='user_upload',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
