# Generated by Django 5.2.1 on 2025-05-12 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_remove_user_upload_type_user_upload_animal_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_upload',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='user_sighting_images/'),
        ),
    ]
