# Generated by Django 5.2.1 on 2025-05-12 13:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_user_upload_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_upload',
            name='station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.forest_station'),
        ),
    ]
