# Generated by Django 5.2.1 on 2025-05-16 11:49

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_user_upload_station'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert_to_user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alert_to_user',
            name='target_audience',
            field=models.CharField(choices=[('ALL', 'All Users'), ('NEAR_STATION', 'Users Near a Specific Station')], default='ALL', max_length=20),
        ),
        migrations.AddField(
            model_name='alert_to_user',
            name='target_station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.forest_station'),
        ),
        migrations.AddField(
            model_name='camera_alerts',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user_table',
            name='STATION',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.forest_station'),
        ),
        migrations.AlterField(
            model_name='user_table',
            name='first_name',
            field=models.CharField(max_length=90),
        ),
    ]
