# Generated by Django 5.2.1 on 2025-05-16 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alert_to_user_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_table',
            name='STATION',
        ),
    ]
