# Generated by Django 5.2.1 on 2025-05-16 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_remove_user_table_station'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_table',
            name='STATION',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.forest_station'),
        ),
    ]
