# Generated by Django 5.2.1 on 2025-05-16 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_user_table_station'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert_to_user',
            name='is_seen',
            field=models.BooleanField(default=False),
        ),
    ]
