# Generated by Django 5.2.1 on 2025-05-18 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_alert_to_user_is_seen'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.forest_station'),
        ),
    ]
