# Generated by Django 5.2.1 on 2025-05-20 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_camera_station'),
    ]

    operations = [
        migrations.CreateModel(
            name='TechSupportRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_type', models.CharField(choices=[('detection_system', 'Detection System'), ('camera', 'Camera'), ('other', 'Other')], max_length=50)),
                ('description', models.TextField()),
                ('request_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('dispatched', 'Tech Support Person Dispatched'), ('resolved', 'Resolved')], default='pending', max_length=50)),
                ('resolution_notes', models.TextField(blank=True, null=True)),
                ('resolved_date', models.DateTimeField(blank=True, null=True)),
                ('OFFICER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.forest_officer')),
            ],
        ),
    ]
