# Generated by Django 5.2.1 on 2025-05-20 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_techsupportrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_table',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='user_images/'),
        ),
    ]
