# Generated by Django 5.2.1 on 2025-05-21 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_remove_complaints_date_complaints_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaints',
            name='reply',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
