# Generated by Django 5.2.1 on 2025-05-21 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_alter_complaints_reply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaints',
            name='complaint',
            field=models.TextField(),
        ),
    ]
