# Generated by Django 5.2.1 on 2025-05-21 07:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_alter_complaints_complaint'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaints',
            name='STATION',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.forest_station'),
        ),
        migrations.AddField(
            model_name='complaints',
            name='contact_number',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
