# Generated by Django 5.2.1 on 2025-05-21 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_complaints_station_complaints_contact_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curfew_info',
            name='threat_level',
            field=models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], default='Unknown', max_length=50),
        ),
    ]
