# Generated by Django 5.2.1 on 2025-05-22 09:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_alter_curfew_info_threat_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='SafetyTip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="Title of the safety tip (e.g., 'Bear Encounter Safety')", max_length=200)),
                ('thumbnail', models.ImageField(help_text="Thumbnail image for the tip's card display", upload_to='thumbnails/')),
                ('description', models.TextField(blank=True, help_text='Optional: A brief summary of the tip.')),
                ('content_type', models.CharField(choices=[('image_gallery', 'Image Gallery'), ('pdf_document', 'PDF Document')], default='image_gallery', help_text='Choose whether this tip is an image gallery or a PDF document.', max_length=20)),
                ('pdf_file', models.FileField(blank=True, help_text="Upload a PDF file if 'PDF Document' is selected. Leave blank for image galleries.", null=True, upload_to='pdfs/')),
                ('category', models.CharField(blank=True, help_text="Optional: Category for filtering (e.g., 'Animal Encounters', 'Survival', 'First Aid').", max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Safety Tip',
                'verbose_name_plural': 'Safety Tips',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='SafetyTipImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Upload an image for this gallery.', upload_to='tip_images/')),
                ('caption', models.CharField(blank=True, help_text='Optional: Caption for the image.', max_length=255)),
                ('order', models.PositiveIntegerField(default=0, help_text='Order of the image in the gallery.')),
                ('safety_tip', models.ForeignKey(help_text='Select the Safety Tip (must be an Image Gallery type) this image belongs to.', limit_choices_to={'content_type': 'image_gallery'}, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='myapp.safetytip')),
            ],
            options={
                'verbose_name': 'Safety Tip Image',
                'verbose_name_plural': 'Safety Tip Images',
                'ordering': ['order'],
            },
        ),

    ]
