# Generated by Django 5.2.1 on 2025-05-22 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_safetytip_safetytipimage_delete_safety_tips'),
    ]

    operations = [
        # migrations.DeleteModel(
        #     name='safety_tips',
        # ),
        migrations.AlterField(
            model_name='safetytipimage',
            name='caption',
            field=models.TextField(blank=True, help_text='Optional: Caption for the image.'),
        ),
    ]
