# Generated by Django 5.2.1 on 2025-05-23 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_delete_safety_tips_alter_safetytipimage_caption'),
    ]

    operations = [
        migrations.CreateModel(
            name='DangerousArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geojson_data', models.JSONField(help_text='GeoJSON representation of the dangerous area polygon.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by_officer', models.ForeignKey(blank=True, help_text='The forest officer who created this dangerous area.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_dangerous_areas', to='myapp.forest_officer')),
            ],
            options={
                'verbose_name': 'Dangerous Area',
                'verbose_name_plural': 'Dangerous Areas',
            },
        ),
        # migrations.DeleteModel(
        #     name='safety_tips',
        # ),
        migrations.AddField(
            model_name='forest_station',
            name='latitude',
            field=models.FloatField(blank=True, help_text="Latitude of the station's center point", null=True),
        ),
        migrations.AddField(
            model_name='forest_station',
            name='longitude',
            field=models.FloatField(blank=True, help_text="Longitude of the station's center point", null=True),
        ),
        migrations.AddField(
            model_name='dangerousarea',
            name='station',
            field=models.ForeignKey(help_text='The forest station/area this dangerous zone belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='dangerous_areas', to='myapp.forest_station'),
        ),
    ]
