# Generated by Django 5.2.1 on 2025-05-24 08:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_dangerousarea_delete_safety_tips_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrekkingPass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valid_from', models.DateTimeField()),
                ('valid_to', models.DateTimeField()),
                ('instructions', models.TextField(help_text='Instructions/conditions for the trekking pass')),
                ('pass_pdf', models.FileField(blank=True, help_text='Generated PDF of the trekking pass', null=True, upload_to='trekking_passes/')),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('issued_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_trekking_passes', to='myapp.forest_officer')),
            ],
            options={
                'ordering': ['-issued_at'],
            },
        ),
        migrations.CreateModel(
            name='TrekkingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('phone', models.BigIntegerField()),
                ('email', models.CharField(max_length=100)),
                ('id_card_pdf', models.FileField(help_text="PDF of user's ID card", upload_to='trekking_id_cards/')),
                ('trekkers_count', models.IntegerField(default=1, help_text='Number of people in the trekking group')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('destination', models.CharField(help_text='Specific area or route for trekking', max_length=255)),
                ('purpose', models.TextField(blank=True, help_text='Brief purpose of the trekking')),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('officer_notes', models.TextField(blank=True, help_text='Notes from the reviewing officer')),
                ('reviewed_by_officer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_trekking_requests', to='myapp.forest_officer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trekking_requests', to='myapp.user_table')),
            ],
            options={
                'ordering': ['-requested_at'],
            },
        ),
        # migrations.DeleteModel(
        #     name='safety_tips',
        # ),
        migrations.AddField(
            model_name='trekkingpass',
            name='request',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trekking_pass', to='myapp.trekkingrequest'),
        ),
    ]
