# Generated by Django 5.2.1 on 2025-05-25 07:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_trekkingpass_trekkingrequest_delete_safety_tips_and_more'),
    ]

    operations = [
        # migrations.DeleteModel(
        #     name='safety_tips',
        # ),
        migrations.AddField(
            model_name='trekkingrequest',
            name='station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trekking_requests', to='myapp.forest_station'),
        ),
    ]
