# Generated by Django 5.2.1 on 2025-05-27 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0025_passwordresettoken_delete_safety_tips'),
    ]

    operations = [
        # migrations.DeleteModel(
        #     name='safety_tips',
        # ),
    ]
