# Generated by Django 5.2.1 on 2025-05-28 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0026_delete_safety_tips'),
    ]

    operations = [
        # migrations.DeleteModel(
        #     name='safety_tips',
        # ),
        migrations.AlterField(
            model_name='forest_officer',
            name='address',
            field=models.TextField(),
        ),
    ]
