# Generated by Django 5.2.1 on 2025-05-30 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0027_delete_safety_tips_alter_forest_officer_address'),
    ]

    operations = [
        # migrations.DeleteModel(
        #     name='safety_tips',
        # ),
        migrations.AlterField(
            model_name='contacts',
            name='details',
            field=models.TextField(),
        ),
    ]
