# Generated by Django 5.2.1 on 2025-05-30 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0028_delete_safety_tips_alter_contacts_details'),
    ]

    operations = [
        # migrations.DeleteModel(
        #     name='safety_tips',
        # ),
        migrations.AddField(
            model_name='admin_notification',
            name='display_name',
            field=models.CharField(blank=True, help_text='Optional: A custom name for this notification file.', max_length=255, null=True),
        ),
    ]
