# Generated by Django 5.2.1 on 2025-05-30 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0029_delete_safety_tips_admin_notification_display_name'),
    ]

    operations = [
        # migrations.DeleteModel(
        #     name='safety_tips',
        # ),
        migrations.AddField(
            model_name='animal',
            name='is_core_animal',
            field=models.BooleanField(default=False, help_text='Core animals cannot be deleted and their names cannot be changed.'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='animal_images/'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
