# Generated by Django 5.2.1 on 2025-06-01 17:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0030_delete_safety_tips_animal_is_core_animal_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SightingLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sighting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='myapp.user_upload')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sighting_likes', to='myapp.regularuserlogin')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('sighting', 'user')},
            },
        ),
        # migrations.DeleteModel(
        #     name='safety_tips',
        # ),
    ]
