# Generated by Django 5.2.1 on 2025-06-03 16:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0031_sightinglike_delete_safety_tips'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfficerPasswordResetToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('officer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.forest_officer')),
            ],
        ),
        # migrations.DeleteModel(
        #     name='safety_tips',
        # ),
        migrations.AlterField(
            model_name='user_upload',
            name='status',
            field=models.CharField(choices=[('verified', 'Verified'), ('pending_investigation', 'Pending Investigation'), ('inconclusive', 'Inconclusive')], default='pending_investigation', max_length=30),
        ),
    ]
