# Generated by Django 5.2.1 on 2025-06-06 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0032_officerpasswordresettoken_delete_safety_tips_and_more'),
    ]

    operations = [
        # migrations.DeleteModel(
        #     name='safety_tips',
        # ),
        migrations.AddField(
            model_name='alert_to_user',
            name='camera_latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alert_to_user',
            name='camera_longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
