# Generated by Django 5.2.1 on 2025-06-06 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0033_delete_safety_tips_alert_to_user_camera_latitude_and_more'),
    ]

    operations = [
        # migrations.DeleteModel(
        #     name='safety_tips',
        # ),
        migrations.AlterField(
            model_name='alert_to_user',
            name='target_audience',
            field=models.CharField(choices=[('ALL', 'All Users'), ('OWN_STATION', "Users Near Officer's Own Station")], default='ALL', max_length=20),
        ),
    ]
