# Generated by Django 5.2.1 on 2025-06-09 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0034_delete_safety_tips_and_more'),
    ]

    operations = [
        # migrations.DeleteModel(
        #     name='safety_tips',
        # ),
        migrations.AlterField(
            model_name='techsupportrequest',
            name='issue_type',
            field=models.CharField(choices=[('detection_system', 'Detection System'), ('camera', 'Camera Hardware/Feed'), ('network', 'Network Connectivity'), ('account', 'Account or Website Problem'), ('other', 'Other')], max_length=50),
        ),
    ]
