# Generated by Django 5.2.1 on 2025-06-11 03:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0035_delete_safety_tips_and_more'),
    ]

    operations = [
        # migrations.DeleteModel(
        #     name='safety_tips',
        # ),
        migrations.AlterField(
            model_name='forest_officer',
            name='STATION',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.forest_station'),
        ),
    ]
