# Generated by Django 5.2.16 on 2026-08-03 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0036_delete_safety_tips_alter_forest_officer_station'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(
                    name='safety_tips',
                ),
            ],
            database_operations=[],
        ),
    ]
