# Generated by Django 5.2.16 on 2026-08-03 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0037_delete_safety_tips'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert_to_user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='alert_to_user',
            name='is_seen',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='camera_alerts',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='camera_alerts',
            name='date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='trekkingrequest',
            name='requested_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='trekkingrequest',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], db_index=True, default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='user_table',
            name='email',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='user_table',
            name='phone',
            field=models.BigIntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='user_upload',
            name='date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='user_upload',
            name='status',
            field=models.CharField(choices=[('verified', 'Verified'), ('pending_investigation', 'Pending Investigation'), ('inconclusive', 'Inconclusive')], db_index=True, default='pending_investigation', max_length=30),
        ),
    ]
