"""
Django settings for wildeye project.

Generated by 'django-admin startproject' using Django 3.2.25.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""
import mimetypes
import os
from pathlib import Path

from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load .env file from root or backend directory
env_path = BASE_DIR.parent / '.env'
if env_path.exists():
    load_dotenv(dotenv_path=env_path)
else:
    load_dotenv(dotenv_path=BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-9bbf4ow(^ywihgm(-wdc#)i^+8j89l9e2msukx_op=az5ev_f0')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'True').lower() in ('true', '1', 't')

# Email Backend Settings
EMAIL_BACKEND = os.getenv('EMAIL_BACKEND', 'django.core.mail.backends.smtp.EmailBackend')
EMAIL_HOST = os.getenv('EMAIL_HOST', 'smtp.gmail.com')
EMAIL_PORT = int(os.getenv('EMAIL_PORT', 587))
EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS', 'True').lower() in ('true', '1', 't')
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', '@gmail.com')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', 'enter gmail app password here')
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', EMAIL_HOST_USER)
SERVER_EMAIL = os.getenv('SERVER_EMAIL', EMAIL_HOST_USER)

FRONTEND_RESET_URL_BASE = os.getenv('FRONTEND_RESET_URL_BASE', '')

allowed_hosts_str = os.getenv('ALLOWED_HOSTS', '*')
ALLOWED_HOSTS = [h.strip() for h in allowed_hosts_str.split(',') if h.strip()]






# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # 'django.contrib.gis',  # Add GeoDjango for selecting map areas
    'rest_framework',
    'myapp.apps.MyappConfig',
    'map_data',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# Conditionally enable django-silk and debug_toolbar in development mode
if DEBUG:
    try:
        import silk  # noqa: F401
        INSTALLED_APPS.append('silk')
        MIDDLEWARE.insert(0, 'silk.middleware.SilkyMiddleware')
    except ImportError:
        pass

    try:
        import debug_toolbar  # noqa: F401
        INSTALLED_APPS.append('debug_toolbar')
        MIDDLEWARE.insert(0, 'debug_toolbar.middleware.DebugToolbarMiddleware')
    except ImportError:
        pass


ROOT_URLCONF = 'wildeye.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')]
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'myapp.context_processors.officer_profile_context', # Add this line
            ],
        },
    },
]

WSGI_APPLICATION = 'wildeye.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': os.getenv('DB_ENGINE', 'django.db.backends.mysql'),
        'NAME': os.getenv('DB_NAME', 'wildeye_new'),
        'USER': os.getenv('DB_USER', 'root'),
        'PASSWORD': os.getenv('DB_PASSWORD', '123456789'),
        'HOST': os.getenv('DB_HOST', 'localhost'),
        'PORT': os.getenv('DB_PORT', '3306'),
        'OPTIONS': {
            'sql_mode': 'STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION',
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
        },
    }
}



# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_TZ = True

DISPLAY_TIME_ZONE = 'Asia/Kolkata' # Or your desired display timezone



# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS=[
    os.path.join(BASE_DIR,'static')
]
MEDIA_URL='/media/'
MEDIA_ROOT=os.path.join(BASE_DIR, 'media')
# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Add or override the MIME type for .css files
# The second argument (None) is for encoding
mimetypes.add_type("text/css", ".css", strict=True)

# Optional: Add or override for .js if you want to get rid of that warning too
# Standard JS MIME types are text/javascript or application/javascript
# Use application/javascript as it's more modern
mimetypes.add_type("application/javascript", ".js", strict=True)




# You might also want to add this for DRF if you haven't already
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework.authentication.SessionAuthentication',
        # 'rest_framework.authentication.BasicAuthentication', # Optional, if you want basic auth too
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.AllowAny', # Default, but our custom permission will override for specific views
    ),
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 100 # Adjust page size as needed for your API results
}

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose', # Use verbose for more detail during debugging
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO', # Set to INFO for general, or DEBUG for more detail including Django's own debug logs
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': 'INFO', # Or 'DEBUG' to see Django's SQL queries, etc.
            'propagate': False,
        },
        'myapp': { # <--- REPLACE 'your_app_name' with the actual name of your app
            'handlers': ['console'],
            'level': 'DEBUG', # This is crucial for seeing your custom debug messages
            'propagate': True, # Or False if you don't want it to also go to root logger handlers
        },
    }
}









# # Explicitly set MIME types for development server if needed
# if DEBUG:
#     import mimetypes
#     mimetypes.add_type("text/css", ".css")
#     mimetypes.add_type("application/javascript", ".js")
#     # It's also good practice to add the old type mapping to ensure compatibility,
#     # though adding the correct ones first is key.
#     mimetypes.add_type("application/x-css", ".css") # Optional, for leniency
#     mimetypes.add_type("application/x-js", ".js")   # Optional, for leniency
#     # You might also add other common types if you encounter issues later
#     # mimetypes.add_type("application/json", ".json")
#     # mimetypes.add_type("image/svg+xml", ".svg")
#     # mimetypes.add_type("image/png", ".png")
#     # mimetypes.add_type("image/jpeg", ".jpg")
#     # mimetypes.add_type("image/jpeg", ".jpeg")

# LOGIN_URL = '/login/'




# import os
#
# # --- GeoDjango / GDAL settings ---
# if os.name == 'nt': # Apply this only if running on Windows
#     # Explicitly point GeoDjango to the GDAL library DLL
#     # Replace 'C:\\path\\to\\your\\gdalXXX.dll' with the actual path you found
#     # Use raw string (r'...') or double backslashes ('\\') for the path
#     GDAL_LIBRARY_PATH = r'C:\OSGeo4W\bin\gdal301.dll'
#
#     # Example if using OSGeo4W default install:
#     # GDAL_LIBRARY_PATH = r'C:\OSGeo4W64\bin\gdal301.dll' # Adjust DLL name if needed
#
#     # Example if using a wheel installed into your Python env (check actual path!):
#     # GDAL_LIBRARY_PATH = r'C:\Users\itsfe\AppData\Local\Programs\Python\Python36\Lib\site-packages\osgeo\gdal301.dll' # Adjust DLL name and path

# import os
#
# Security & Deployment Settings
SECURE_HSTS_SECONDS = int(os.getenv('SECURE_HSTS_SECONDS', '31536000' if not DEBUG else '0'))
SECURE_HSTS_INCLUDE_SUBDOMAINS = os.getenv('SECURE_HSTS_INCLUDE_SUBDOMAINS', 'True' if not DEBUG else 'False').lower() in ('true', '1', 't')
SECURE_HSTS_PRELOAD = os.getenv('SECURE_HSTS_PRELOAD', 'True' if not DEBUG else 'False').lower() in ('true', '1', 't')
SECURE_SSL_REDIRECT = os.getenv('SECURE_SSL_REDIRECT', 'True' if not DEBUG else 'False').lower() in ('true', '1', 't')
SESSION_COOKIE_SECURE = os.getenv('SESSION_COOKIE_SECURE', 'True' if not DEBUG else 'False').lower() in ('true', '1', 't')
CSRF_COOKIE_SECURE = os.getenv('CSRF_COOKIE_SECURE', 'True' if not DEBUG else 'False').lower() in ('true', '1', 't')

# Sentry Monitoring Initialization
SENTRY_DSN = os.getenv('SENTRY_DSN', '')
if SENTRY_DSN:
    try:
        import sentry_sdk
        from sentry_sdk.integrations.django import DjangoIntegration

        sentry_sdk.init(
            dsn=SENTRY_DSN,
            integrations=[DjangoIntegration()],
            traces_sample_rate=float(os.getenv('SENTRY_TRACES_SAMPLE_RATE', '0.1')),
            send_default_pii=False,
        )
    except Exception as e:
        logger.warning(f"Sentry SDK initialization skipped: {e}")

